/**
 * Type definitions for the Prayer Notification System
 */


/**
 * Represents a single prayer notification to be scheduled
 */
export interface PrayerNotification {
  /** Prayer name (e.g., "Fajr", "Dhuhr") */
  name: string;

  /** Time when the prayer begins (e.g., "05:30 AM") */
  time: string;

  /** ISO timestamp when the notification should trigger */
  triggerTime: Date;

  /** Unique identifier for this notification (generated by expo-notifications) */
  notificationId?: string;
}

/**
 * Prayer names as a union type for type safety
 */
export type PrayerName = "fajr" | "dhuhr" | "asr" | "maghrib" | "isha";

/**
 * Stored notification metadata for persistence
 * Supports multi-day scheduling (today + tomorrow)
 */
export interface StoredNotificationData {
  /** Date when this schedule was created (YYYY-MM-DD) */
  scheduledDate: string;

  /** Notification data for today */
  today: {
    date: string;
    notificationIds: string[];
    dataHash: string;
  };

  /** Notification data for tomorrow */
  tomorrow: {
    date: string;
    notificationIds: string[];
    dataHash: string;
  };

  /** ISO timestamp when this data was created */
  createdAt: string;

  /** Location coordinates used for this schedule */
  location: {
    latitude: number;
    longitude: number;
  } | null;

  /** Timezone used for this schedule */
  timezone?: string;
}

/**
 * Result of a notification scheduling operation
 */
export interface ScheduleResult {
  /** Whether the operation was successful */
  success: boolean;

  /** Number of notifications scheduled */
  scheduledCount: number;

  /** Error message if operation failed */
  error?: string;

  /** Array of scheduled notification IDs */
  notificationIds?: string[];
}

/**
 * Permission status for notifications
 */
export interface NotificationPermissionStatus {
  /** Whether notifications are granted */
  granted: boolean;

  /** Whether the user can be asked for permission */
  canAskAgain: boolean;

  /** Raw permission status */
  status: "granted" | "denied" | "undetermined";
}
