import { Platform, StatusBar, StyleSheet } from "react-native";
import colors from "../../constants/colors.json";
import { CARD_BACKGROUND, OVERLAY_BACKGROUND } from "./constants";

export const styles = StyleSheet.create({
  overlayContainer: {
    flex: 1,
    backgroundColor: OVERLAY_BACKGROUND,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 60,
  },
  scrollContentContainer: {
    flexGrow: 1,
  },
  contentWrapper: {
    flex: 1,
    justifyContent: "space-between",
    paddingHorizontal: 28,
    paddingBottom: 60,
  },
  topSection: {
    alignItems: "center",
  },
  bottomSection: {
    alignItems: "center",
  },
  iconContainer: {
    backgroundColor: `${colors.gold}1a`,
    borderWidth: 1,
    borderColor: `${colors.gold}33`,
    borderRadius: 999,
    padding: 24,
    marginBottom: 20,
  },
  prayerLabelText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 4,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  prayerNameText: {
    color: "#fff",
    fontSize: 48,
    fontWeight: "600",
    fontFamily: Platform.OS === "ios" ? "Georgia" : "serif",
    marginBottom: 4,
  },
  currentTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  currentTimeText: {
    color: colors.gold,
    marginLeft: 6,
    fontWeight: "600",
  },
  remainingTimePill: {
    backgroundColor: `${colors.gold}1a`,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    marginBottom: 32,
  },
  remainingTimeText: {
    color: colors.gold,
    fontSize: 12,
    fontWeight: "700",
  },
  hadithCard: {
    backgroundColor: CARD_BACKGROUND,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderRadius: 24,
    overflow: "hidden",
  },
  hadithCardImage: {
    borderRadius: 24,
    opacity: 0.3,
    resizeMode: "cover",
  },
  hadithText: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 16,
    lineHeight: 26,
    fontStyle: "italic",
    marginBottom: 12,
  },
  hadithSourceText: {
    color: colors.gold,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  swipeWrapper: {
    width: "100%",
    marginBottom: 16,
  },
  swipeTrack: {
    backgroundColor: CARD_BACKGROUND,
    borderWidth: 2,
    borderColor: `${colors.gold}4d`,
    borderRadius: 64,
    height: 70,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  progressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "100%",
    backgroundColor: colors.gold,
    opacity: 0.15,
  },
  processingContainer: {
    position: "absolute",
    width: "100%",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  processingSpinner: {
    marginRight: 8,
  },
  processingText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  thumbWrapper: {
    position: "absolute",
    left: 6,
    zIndex: 10,
  },
  thumbButton: {
    width: 58,
    height: 58,
    borderRadius: 999,
    backgroundColor: colors.gold,
    alignItems: "center",
    justifyContent: "center",
  },
  swipeLabelText: {
    color: "rgba(255,255,255,0.5)",
    textAlign: "center",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  reminderContainer: {
    marginBottom: 16,
    width: "100%",
    overflow: "hidden",
  },
  reminderContainerCollapsed: {
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    borderRadius: 16,
    padding: 0,
  },
  reminderContainerExpanded: {
    backgroundColor: CARD_BACKGROUND,
    borderWidth: 1,
    borderColor: `${colors.gold}33`,
    borderRadius: 20,
    padding: 16,
  },
  reminderHeaderCollapsed: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 32,
    marginBottom: 0,
  },
  reminderHeaderExpanded: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginBottom: 12,
  },
  reminderHeaderIcon: {
    marginRight: 8,
  },
  reminderHeaderTextCollapsed: {
    color: "rgba(255,255,255,0.6)",
    fontWeight: "700",
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  reminderHeaderTextExpanded: {
    color: colors.gold,
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  reminderEndsText: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 10,
    marginLeft: "auto",
    marginRight: 8,
  },
  reminderChevronCollapsed: {
    position: "absolute",
    right: 16,
  },
  reminderChevronExpanded: {
    position: "relative",
    right: 0,
  },
  reminderOptionButton: {
    backgroundColor: `${colors.gold}1f`,
    borderWidth: 1,
    borderColor: `${colors.gold}4d`,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  reminderOptionMinutesText: {
    color: colors.gold,
    fontWeight: "700",
    fontSize: 13,
  },
  reminderOptionTimeText: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 10,
    marginTop: 2,
  },
});
